---
title: "Output - Table S2"
output: html_notebook
---

```{r setup, include=FALSE}
source("../../code/0-setup/1-setup.R")
library("table1")
```

```{r data_input, include=FALSE}
calgem_production <-
  readRDS("../../data/interim/calgem_production_monthly.rds")
```

```{r data_tidying, include=FALSE}
# wells dataset
aqs_monitors <- aqs_daily_annuli_exposure %>%
  select(monitor_id, near_wells, is_urban, carb_basin,
         pm25_mean, co_max, no2_max, o3_max, vocs_total) %>%
  group_by(monitor_id) %>%
  summarize(near_wells = near_wells,
            is_urban   = is_urban,
            carb_basin = carb_basin,
            pm25_mean  = mean(pm25_mean, na.rm = TRUE),
            co_mean    = mean(co_max, na.rm = TRUE),
            no2_mean   = mean(no2_max, na.rm = TRUE),
            o3_mean    = mean(o3_max, na.rm = TRUE),
            vocs_mean  = mean(vocs_total, na.rm = TRUE)) %>%
  mutate(exposed_pm25 = case_when(pm25_mean >= 0   ~ 1,
                                  pm25_mean  < 0   ~ 0,
                                  is.na(pm25_mean) ~ 0),
         exposed_co   = case_when(co_mean >= 0     ~ 1,
                                  co_mean  < 0     ~ 0,
                                  is.na(co_mean)   ~ 0),
         exposed_no2  = case_when(no2_mean >= 0    ~ 1,
                                  no2_mean  < 0    ~ 0,
                                  is.na(no2_mean)  ~ 0),
         exposed_o3   = case_when(o3_mean >= 0     ~ 1,
                                  o3_mean  < 0     ~ 0,
                                  is.na(o3_mean)   ~ 0),
         exposed_vocs = case_when(vocs_mean >= 0   ~ 1,
                                  vocs_mean  < 0   ~ 0,
                                  is.na(vocs_mean) ~ 0)) %>%
  distinct(monitor_id, .keep_all = TRUE)

# well-months dataset
aqs_daily_annuli_exposure <- aqs_daily_annuli_exposure %>%
  mutate(year_category = case_when(year %in% c(2006:2009) ~ "2006-2009",
                                   year %in% c(2010:2014) ~ "2010-2014",
                                   year %in% c(2015:2019) ~ "2015-2019"))

# production-months dataset
```

## Table S2 components

### Monitors data

#### Table. Pollutants by monitor

```{r echo=FALSE}
table_monitors1 <- table1::table1()
table_monitors1
```

#### Table. Wells by basin

```{r echo=FALSE}

```

### Well-months data

#### Table. Monitor-days

```{r echo=FALSE}

```